### ISSUE TITLE
does not work on 1.12

### ISSUE THREAD

**Issue by nextdayy** [Polyfrost/PolySprint#1]
moved https://github.com/Polyfrost/OneConfig/issues/339.

### Bug description

Toggle Sprint mod 1.12.2 doesn't work. When I press shift, it shows sprinting (toggled), and when I walk, it doesn't automatically sprint.

### Steps to reproduce

SKLauncher Minecraft 1.12.2 Forge 14.23.5.2860
My Mods List: PolySprint, Evergreen Hud, OneConfig, Perspective Mod Redux, Namepain, TimeToLive, Controlling, Keystrokes, BetterFps, Optifine, Collective, StackRefill, MacroKey Binding.

**Comment by tdg3001** [comment]
https://github.com/Polyfrost/PolySprint/assets/106243095/1d93d378-d84d-423c-9a30-4f8a31794e00

Bad graphic because upload limit

**Comment by elseawhy** [comment]
had the same exact issue, ran the mod alongside tekkit 2 and it doesnt work even though the ui/hud shows up

**Comment by tdg3001** [comment]
> had the same exact issue, ran the mod alongside tekkit 2 and it doesnt work even though the ui/hud shows up

Yo bro, do it working now?

**Comment by tdg3001** [comment]
Pls Fix 😭😭

**Comment by Wyvest** [comment]
Will be fixed in V1
